# -*- coding: utf-8 -*-
"""Spotify_Project2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ujIsSoSZFQGh2J4refTIHFq4xccPl_LR
"""

import requests
import pandas as pd

# Your Spotify API Credentials
client_id = '2cde6a8ff1344b008032186261598e40'
client_secret = 'd7ee27e72ec34f298ec475588417dbf5'

# Function to get Spotify access token
def get_spotify_token(client_id, client_secret):
    auth_url = 'https://accounts.spotify.com/api/token'
    auth_response = requests.post(auth_url, {
        'grant_type': 'client_credentials',
        'client_id': client_id,
        'client_secret': client_secret,
    })
    auth_data = auth_response.json()
    return auth_data['access_token']

# Function to search for a track and get its ID
def search_track(track_name, artist_name, token):
    query = "{} artist:{}".format(track_name, artist_name)
    url = "https://api.spotify.com/v1/search?q={}&type=track".format(query)
    response = requests.get(url, headers={
        'Authorization': 'Bearer {}'.format(token)
    })
    json_data = response.json()
    try:
        first_result = json_data['tracks']['items'][0]
        track_id = first_result['id']
        return track_id
    except (KeyError, IndexError):
        return None

# Function to get track details
def get_track_details(track_id, token):
    url = "https://api.spotify.com/v1/tracks/{}".format(track_id)
    response = requests.get(url, headers={
        'Authorization': 'Bearer {}'.format(token)
    })
    json_data = response.json()
    image_url = json_data['album']['images'][0]['url']
    return image_url


# Get Access Token
access_token = get_spotify_token(client_id, client_secret)

# Read your DataFrame (replace 'spotify_data.csv' with the path to your CSV file)
df_spotify = pd.read_csv('spotify_data.csv', encoding='ISO-8859-1')

# Loop through each row to get track details and add to DataFrame
for i, row in df_spotify.iterrows():
    track_id = search_track(row['track_name'], row['artist_name'], access_token)
    if track_id:
        image_url = get_track_details(track_id, access_token)
        df_spotify.at[i, 'image_url'] = image_url

# Save the updated DataFrame (replace 'updated_file.csv' with your desired output file name)
df_spotify.to_csv('updated_file.csv', index=False)
